### ISSUE TITLE
New minikerberos lib broke aiosmb

### ISSUE THREAD

**Issue by legra-ms** [skelsec/aiosmb#15]
Issue is here:

https://github.com/skelsec/aiosmb/blob/master/aiosmb/authentication/kerberos/gssapi.py#L7

Referencing https://github.com/skelsec/minikerberos/issues/23

**Comment by daddycocoaman** [comment]
Used the wrong account to post this but it stands. :P

**Comment by skelsec** [comment]
ahh! okay this makes sense now, the issue was sent to minikerberos initially without metioning where the issue is.

**Comment by skelsec** [comment]
pushed the aiosmb version we have at Porchetta so the code should work now

**Comment by legra-ms** [comment]
It works. Thanks!
