### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by noraj** [skelsec/aiosmb#34]
1. You still have the MIT classifier https://github.com/skelsec/aiosmb/blob/5f686cad442ffe472fb58a401225c180dfe38e63/setup.py#L57
2. As said previously having no license is worse than anything see https://github.com/skelsec/aiosmb/pull/4#issuecomment-1242817126, and see https://choosealicense.com/no-permission/
3. Having no license also violate the Impacket Apache 1.1 License as you don't include Impacket copyright (Forta) and don't include Impacket license.
    - Apache License 1.0 (Apache-1.0) https://www.tldrlegal.com/license/apache-license-1-0-apache-1-0
    - Apache License 2.0 (Apache-2.0) https://www.tldrlegal.com/license/apache-license-2-0-apache-2-0

So I think the easiest thing to do would be to adopt Apache 1.1 License (see https://www.apache.org/licenses/) for aiosmb (and other similar projects) and to included Impacket copyright and license for the relevant files.

**Comment by skelsec** [comment]
You are right abt the MIT license part. I have added a License.md file now and the offending line removed from the setup.py script.  
Hope this is now resolved.

**Comment by noraj** [comment]
Sounds ok 👍🏻
